# Generated by Django 3.2 on 2023-03-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.BigIntegerField()),
                ('advertiser_id', models.BigIntegerField()),
                ('country', models.CharField(max_length=5)),
                ('price', models.FloatField()),
                ('event_type_id', models.IntegerField()),
                ('gdpr', models.IntegerField()),
                ('min_cpm', models.FloatField()),
                ('priority', models.FloatField()),
                ('bid_price', models.FloatField()),
            ],
        ),
    ]
